media:
  input: jekyll-site/assets/images
  output: /assets/images

content:
  - name: pages
    label: Pages
    type: collection
    path: jekyll-site/pages
    format: yaml-frontmatter
    view:
      fields: [title, description]
    fields:
      - label: Layout
        name: layout
        type: string
        hidden: true
        default: default
      - label: Title
        name: title
        type: string
      - label: Description
        name: description
        type: text
      - label: Permalink
        name: permalink
        type: string
        hidden: true
      - label: Body
        name: body
        type: rich-text
  - name: config
    label: Jekyll config
    path: jekyll-site/_config.yml
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
        description: Will be used for any page with no description.
      - name: url
        label: Website URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: cover
        label: Preview image
        type: image
        description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)